### ISSUE TITLE
Duplicate read IDs with distinct sequences in output

### ISSUE THREAD

**Issue by julienlag** [lh3/minimap2#113]
Hello, 
thanks for writing this very promising tool.
I've just found something strange that I believe is a bug. Here's how to reproduce it (a MWE is available in http://genome.crg.es/~jlagarde/tmp/minimap2/):
```
$ minimap2 --version
2.8-r672
$ minimap2 --cs  --secondary=no  -L -ax splice mm10.fa test.fastq > test.sam
```
The input FASTQ contains only one read. However, as can be seen in the output, the corresponding read ID appears twice in the output SAM, but with different sequences (field 10): the first record contains the original sequence, as seen in the FASTQ, whereas the second one contains some kind of partial reverse-complement of the original.

Could you please look into this?
Thanks in advance,
Julien

**Comment by lh3** [comment]
You are looking at a chimeric alignment, which is caused by a common artifact in PacBio reads. Here, the first half of the read is approximately the reverse complement of the second half. Minimap2 aligned the two parts to the same chromosomal position but onto the opposite strands.

Like bwa-mem, minimap2 applies hard clipping to the second half of read. With hard clipping, column 10 only shows the sequence in alignment (i.e. it is a subsequence), not the entire sequence.

**Comment by lh3** [comment]
Just to clarify: this is not a bug. The weird alignment you see is a command PacBio artifact.

**Comment by julienlag** [comment]
thanks for the quick reply!
I understand. Would a `samtools view -F 256 -F4 -F 2048` on the SAM file filter out records such as the second "supplementary" (FLAG 2048) alignment, on top of discarding non-primary ones?
My goal is to (1) keep only one (best) hit for each read, (2) if possible, keep the read sequence intact (i.e. as in FASTQ).
Although the read is chimeric I would argue that the first alignment is still usable and valid.
thanks again
Julien

**Comment by lh3** [comment]
I would discard such reads, but probably it doesn't matter too much either way. The samtools command line should work, I think.

**Comment by julienlag** [comment]
alright thanks, and sorry for calling this a bug

**Comment by lh3** [comment]
Never mind. For general users, it is difficult to get hold of all these weird events. Glad you asked about it.
