### ISSUE TITLE
divergence explanation

### ISSUE THREAD

**Issue by njaupan** [lh3/minimap2#225]
Hi,
Just to be clear, what is exact average divergence for asm5, asm10 and asm20?
It seems to have two versions that
in Manual Reference Pages
asm5 | Only use this preset if the average divergence is far below 5%.
asm10| Up to 10% sequence divergence.
asm20 | Up to 20% sequence divergence.
but in cookbook
asm5 |sequence divergence below 1%.
asm10 |  for divergence around a couple of percent 
asm20  | for divergence not more than 10%.

which one is true?

**Comment by lh3** [comment]
Actually, both wordings are correct. Take "asm5" for example. This preset will always break an alignment when the sequence divergence is above 5%. However, when you have two genomes at 5% divergence, you wouldn't want to use "asm5" because some regions will have >5% divergence by chance and lead to highly fragmented alignments under "asm5". You would probably want to use "asm20" in this case.

In practice, use the general guideline in the cookbook. I will probably change the manpage at some point. Sorry for the confusion. My mistake.

**Comment by njaupan** [comment]
I see, thank you so much. I am closing it now.

**Comment by baozg** [comment]
Following up comment, if you want to align two genomes (like two A.thaliana ecotypes), `asm20` will give you more complete alignment than `asm5`. Follow the `dipcall` confident regions definition, `asm5` only give ~60M, but `asm20` give ~100Mb blocks (ref genome size ~140Mb, 20Mb centromere / rDNA)
