### ISSUE TITLE
Circular genome

### ISSUE THREAD

**Issue by mariuswalter** [lh3/minimap2#248]
Hey!
Do you plan to add a feature to map on circular genome?
That would be awesome!
marius

**Comment by lh3** [comment]
Sorry. I don't see minimap2 will support circular genomes.

**Comment by schorlton** [comment]
Any consideration to reopening this feature request?

Several things have happened since this time:
1. SAM has added support for circular alignments: https://github.com/samtools/hts-specs/commit/f2a6b9921c827465703538a767072a8489983bad
2. Other nanopore aligners have added support for circular genomes: https://github.com/lbcb-sci/graphmap2#features
In my internal eval, it's still better to realign minimap2 mappings:
3. Slightly hack-y solutions have been developed to wrap around aligners for circular mappings: https://github.com/apeltzer/CircularMapper
4. Long-reads continue to get longer, increasing the probability that some of them will wrap around a break in a circular genome
5. Assemblers have started tagging circular assemblies: https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-flye-output

Thanks for your consideration!

**Comment by lh3** [comment]
Minimap2 won't support circular genomes.
