### ISSUE TITLE
MD tag for splice alignment errors

### ISSUE THREAD

**Issue by cheny19** [lh3/minimap2#250]
Dear Heng, 

I downloaded your most recent minimap2 release and wanted to try the MD flag for spliced alignment. However, it seems that minimap2 couldn't parse the argument correctly. Here are the error messages I got:

`~/workspace/minimap2/minimap2-2.13/minimap2 --md -t 12 -ax splice human_mmi transcripts.fa > test.sam`  

> [ERROR] unknown option in "-t"

I tried to put the `--md` to different places in my command, but it always shows similar error. Then I noticed that there's another excutable called `minimap2.1` in the package, so I tried that. This time I got a different error:

`~/workspace/minimap2/minimap2-2.13/minimap2.1 --md -t 12 -ax splice human_mmi transcripts.fa > test.sam`

> ~/workspace/minimap2/minimap2-2.13/minimap2.1: line 1: .TH: command not found
~/workspace/minimap2/minimap2-2.13/minimap2.1: line 2: .SH: command not found
~/workspace/minimap2/minimap2-2.13/minimap2.1: line 3: .PP: command not found

Could you help me with this issue?

Thanks,
Chen

**Comment by wdecoster** [comment]
I believe you are looking for --MD, in uppercase.

**Comment by cheny19** [comment]
Ooops.. You are right, `--MD` worked. Thanks so much! The error message didn't say it doesn't recognize `--md` while the previous versions said so, so I didn't realize it's that reason. Anyway, I'll close the issue now.

**Comment by lh3** [comment]
The latest minimap2 uses a new command-line parser. I should let minimap2 warn given unknown options. Consider this as a feature request. I will keep it open until I improve it.

**Comment by lh3** [comment]
Minimap2 checks unrecognized options. However, 2.13 wrongly reports the argument next to the missing option. It is now fixed.

**Comment by Wyx2333** [comment]
Dear Heng,

I have come across an issue when I tried to follow your tutorial for using Minimap2. I could not execute the minimap command following the instruction. I would very appreciate it if you could help.

By using,
> curl -L https://github.com/lh3/minimap2/releases/download/v2.17/minimap2-2.17_x64-linux.tar.bz2 | tar jxf -
> cp minimap2-2.17_x64-linux/{minimap2,k8,paftools.js} .  # copy executables

 I got an error message: 
cp: cannot overwrite directory './minimap2' with non-directory

After this, I run after downloading the test data

> minimap2 -ax map-pb -t4 ecoli_ref.fa ecoli_p6_25x_canu.fa > mapped.sam

an error message shows,
No command 'minimap2' found, did you mean:
 Command 'minimap' from package 'minimap' (universe)
minimap2: command not found

I also tried another installation method, i.e., 

> git clone https://github.com/lh3/minimap2
> cd minimap2 && make

 But still find the problem as "make: Nothing to be done for 'all'.." And then the same error issue "No command 'minimap2' found, did you mean..."

I'm using Ubuntu 16.04.
Thank you so much.

**Comment by wdecoster** [comment]
This is not directly an appropriate place to report your issue, it is not related to the previous question as far as I can tell.

I think you have a directory called 'minimap2' in the current directory where you downloaded the tar.bz2. Therefore the `cp` fails, because you try to copy the executable `minimap2` while there is already a directory `minimap2`. Therefore the command also fails, because it cannot find the executable. You could consider renaming the minimap2 directory you have (if you need it).

**Comment by Wyx2333** [comment]
Thank you. You are right for the copy issue. This is because I have downloaded two many versions of minimap2 as you can see I tried another installation. In contrast,  I delete .tar.bz2 and try to directly use minimap2 directory for the usage which is downloaded via

> git clone https://github.com/lh3/minimap2
> cd minimap2 && make

After adding the current directory on PATH,

> export PATH="$PATH:"`pwd`

I could use minimap2. Thank you, and have a nice day.

**Comment by wdecoster** [comment]
To make installation easier you could have a look at conda and bioconda.
If you have conda installed you should just do `conda install -c bioconda minimap2` and everything should be properly installed.

**Comment by Wyx2333** [comment]
Thanks for the advice.  I’m new to Ubuntu&&bioinformatics. Your information is of value to me :)
