### ISSUE TITLE
which mapper to use, and bwa to minimap2 eqiuvalent functions

### ISSUE THREAD

**Issue by devonorourke** [lh3/minimap2#256]
Good morning, 
I was wondering if there are equivalent arguments to pass between `bwa` and `minimap2`:  I'm trying to align some Hi-C data generated by Phase Genomics, and [they recommend](https://phasegenomics.github.io/2019/09/19/hic-alignment-and-qc.html) aligning with `bwa` using the `-5`, `-S`, and `-P` flags. 
I'm not quite sure if it's even better to use minimap2 over bwa, and can appreciate that certain circumstances may favor one mapper over another. Within the [hickit](https://github.com/lh3/hickit#aligning-hi-c-reads) example, it shows using bwa as the aligner, but then mentions that it also works with minimap2. 
I'm curious if:
a) there are specific minimap2 parameters to pass to make it perform like the `-5SP` parameters used in bwa mem;
b) there is any reason, other than speed, to use minimap over bwa in this specific mapping circumstance?

Thank you very much

**Comment by lh3** [comment]
Minimap2 doesn't implement "-S" in bwa-mem. Option "--no-pairing" corresponds to "-P" of bwa-mem. Minimap2 doesn't have a "-5" behavior, but the feature is usually not critical to Hi-C. Hickit doesn't rely on "-5", either.

Hi-C hits are shorter due to split/"chimeric" reads. Bwa-mem is more sensitive to such hits than minimap2 and is thus the preferred choice.

**Comment by devonorourke** [comment]
Perfect. Thanks for the clarification.

**Comment by DelphIONe** [comment]
Hi, 

I have a simple question but I need your help please :-)
I use these parameters with bwa mem command (good results) :
bwa mem -W 13 -k 6 -x ont2d 

Now, I would like use Tombo and for the resquiggle step, Tombo need minimap2 alignment or index.
Can you help me to find the equivalent command with minimap2 ?
I have tried minimap2 -k 6 -w 13 -a -x map-ont 
minimap2 -k 6 -m 13 -a -x map-ont
minimap2 -k 6 -g 13 -a -x map-ont

even minimap2 -k 6 -m 13 -sr -a because my reads are ~200 pb but it still Nanopore reads...
I can't find a satisfactory result.

Help me please !
Thanks a lot,
