### ISSUE TITLE
MAPQ

### ISSUE THREAD

**Issue by sarah872** [lh3/minimap2#297]
Coming from a very useful post: [http://www.acgt.me/blog/2015/3/17/more-madness-with-mapq-scores-aka-why-bioinformaticians-hate-poor-and-incomplete-software-documentation](url), the mapping quality depends on the program used. What's the range of MAPQ that `minimap2` uses?

**Comment by lh3** [comment]
0–60.

That blog post is complaining too much, IMO. For complex tasks, tools typically employ many heuristics and internal logic. It is not possible to document all of them. If you think some missing information is important, point it out or better create a PR. Tophat is well documented in general. It is not necessary to accuse it that much just because it doesn't say how its mapq is scaled.

**Comment by npavlovikj** [comment]
@lh3 , I am sorry for reopening this issue, but I have somewhat related question.
In the Minimap2 paper, it is mentioned that the mapping quality for each primary chain is calculated as:
```
mapQ = 40 · (1 − f2/f1) · min{1, m/10} · log f1
```

Is this the MAPQ value reported in the MAPQ field of the SAM format, or is in one of the other Minimap2 flags?
