### ISSUE TITLE
Question on ts:A:- reads

### ISSUE THREAD

**Issue by ljw90607** [lh3/minimap2#366]
Dear @lh3,

Hello, I had a question on my minimap2 mapped nanopore cDNA PCR data.
As I classified the data by ts tag, I noticed that there are 2.5 times more ts:A:- reads than ts:A:+.
Even the number of unclassified reads (no ts tag) top the number of other 2 tagged types.
(ts:A:+ grep count: 730k , ts:A:- grep count: 1.84mil, no tag count: 2.58 mil)
What could be the issue of such data? 

Also, If I were to obtain the mapped output all positively stranded to the reference,
would it be possible to correct the reads that are ts:A:- or non-tagged reads to ts:A:+ by correcting their sequence in reverse complementary manner?

Thank you for your generous help.

Jungwoo.

**Comment by lh3** [comment]
If there are many reads without the tag, probably those are very short and don't span splicing sites. That could be a library problem. Knowing little the library prep and not looking at the data, I am not the best person to answer your question.

> would it be possible to correct the reads that are ts:A:- or non-tagged reads to ts:A:+ by correcting their sequence in reverse complementary manner?

You can do that. Nonetheless, this is not "correcting" because there is nothing wrong with reads with ts:A:-. cDNA reads should come from both strands.
