### ISSUE TITLE
avx2 rebase

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#543]
Hey Heng,

I'm really interested in testing the AVX2 implementation again. The faster I make everything else, minimap2 suddenly pops up in the profiler :) Would it be possible that you update the `avx` branch with `master` such that I can simply switch branches in my tests?
I've tried just cherrypicking, but internal interfaces have changed over the course of time.

Thanks,
Armin

**Comment by lh3** [comment]
I have merged master into the avx branch. There are conflicts, but I don't know if it is working properly.

I need to allocate a large chunk of my time to minimap2 at some point.

**Comment by armintoepfer** [comment]
That would be great. A little bit more data, `ccs` spends 12% of its time in `ksw_extd2_sse41`.

**Comment by boegel** [comment]
I'm also interested in getting `minimap2` working with AVX* instructions.

`minimap2` seems to be a bottleneck in some workflows running on our HPC clusters, so I'm hoping for some significant speedups by using AVX, AVX2 & AVX512 instructions where appropriate.

In any case, it seems like the latest `minimap2` version (2.17) isn't using all the resources provided by modern processors (to put it mildly) since it's only using SSE 4.1...

Is there any estimate of what kind of speedup could be achieved when also using AVX* instructions?

**Comment by lh3** [comment]
> Is there any estimate of what kind of speedup could be achieved when also using AVX* instructions?

~10% ish, depending on the type of input data.
