### ISSUE TITLE
Absence of 'mappy.c' file due to gitignore mis-configuration?

### ISSUE THREAD

**Issue by rboissy** [lh3/minimap2#66]
Hi,

There are alternatives (e.g., pip), but the readme.rst file in minimap2's 
python sub-dir states that mappy can be installed using these commands:

	git clone https://github.com/lh3/minimap2
	cd minimap2
	python setup.py install

The MANIFEST.in directory in a git clone of minimap2's repo lists:

include *.h
include Makefile
include ksw2_dispatch.c
include getopt.c
include main.c
include README.md
include python/mappy.c
include python/cmappy.h
include python/cmappy.pxd
include python/mappy.pyx
include python/README.rst

However, the 'python/mappy.c' file doesn't exist in a clone of
39a96662463c3f0dd8c64c70445fc0261721f010 (Nov. 22, 2017).

This situation leads to this error when executing 
'python setup.py install':

gcc: error: python/mappy.c: No such file or directory

The pattern 'mappy.c' is listed in the repo's .gitignore file, 
but it's not clear why that pattern might affect 'python/mappy.c'?

.cproject
.project
.*.swp
*.a
*.o
*.dSYM
minimap2
mappy.c

https://git-scm.com/docs/gitignore

Thanks for your help!
Robert

**Comment by lh3** [comment]
If you build the mappy extension from a github clone, you need to have [cython](http://cython.org) installed. Cython generates mappy.c from mappy.pyx and cmappy.pxd. We don't commit this file because it is derived.

The tar-ball from the [mappy Pypi page](https://pypi.python.org/pypi/mappy) comes with mappy.c generated by cython. This allows you to run `pip install mappy` without cython. You can download that tar-ball and run `python setup.py build_ext`.

**Comment by rboissy** [comment]
[smrtanalysis@pm-ont-intelE5 ~]$ cython -V
Cython version 0.23.4

In my case, cython was installed, but I'll follow your advice about the use of the tarball.
Thanks again,
Robert
