### ISSUE TITLE
CIGAR strings in "SA" tags differ from the CIGAR strings in the corresponding supplementary alignment records

### ISSUE THREAD

**Issue by fedarko** [lh3/minimap2#724]
Hi, and thank you for developing minimap2! I have two questions about an issue with supplementary alignments.

## Problem description

For records that are part of a supplementary alignment in SAM files generated by minimap2, the CIGAR strings listed in the `SA` tags are different from the CIGAR strings listed for these supplementary alignments' records in the same file. It is not immediately clear which of the two CIGAR strings should be interpreted as the "canonical" CIGAR string for this alignment, or why the CIGAR strings are different.

It looks like this was brought up previously in https://github.com/lh3/minimap2/issues/524#issuecomment-575920828 and in https://github.com/lh3/minimap2/pull/287, which imply that the `SA` CIGAR string should not be relied on in these cases.

## Questions

1. As a general rule, does it make sense to ignore the CIGAR string listed in the `SA` tag -- and to always use the CIGAR string located on that alignment's own line in the SAM file instead?

2. If so, do you think it would make sense to update the documentation to clarify this? From reading the [description of the `SA` tag](https://samtools.github.io/hts-specs/SAMtags.pdf), it was not clear to me that CIGAR strings listed for these alignments were expected to be incorrect. I am happy to submit a PR that updates the README or the FAQ accordingly, in order to help future minimap2 users.

My apologies if I am misunderstanding anything!

## Example showing the problem

This file, [`supplemental_alignment.sam.txt`](https://github.com/lh3/minimap2/files/6252261/supplemental_alignment.sam.txt), is a subset of a SAM file generated by minimap2. This SAM file has been filtered to just the two lines originating from a read named `m54033_180919_161442/4194410/ccs`.
 
Line 1 describes the primary alignment of this read to a reference sequence named `edge_25034`, and includes a reference to a supplementary alignment of this read in a different reference sequence named `edge_34620`. The CIGAR string listed on Line 1 in the `SA:` tag for the `edge_34620` supplementary alignment is **`1136M 3I 5180S`** (spaces added for clarity).
 
Line 2 describes the `edge_34620` supplementary alignment in detail: however, the CIGAR string listed on this line for this supplementary alignment is **`23M 1I 537M 1I 64M 1I 512M 5180H`**, instead.
 
The counts of each operation generally match up (e.g. in both CIGAR strings there are 1,136 M operations) but the alignments represented by these strings are still slightly different.

The exact command to minimap2 used to generate the full SAM file was `minimap2 -ax asm20 [reference FASTA file] [reads FASTQ file] > alignment.sam`; the data is derived from [this BioProject](https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA595610).

### Software versions

minimap2 version: `2.17-r941` (installed using linuxbrew)
Running on Ubuntu version `16.04.7`

**Comment by lh3** [comment]
In minimap2, the SA tag mainly tells you the start and end coordinates of other alignments. It is not intended to keep detailed CIGARs.

**Comment by CharlesARoy** [comment]
Hi @lh3, I am also very grateful for your work in developing Minimap2!

I think that Marcus makes some good points and I'd suggest updating Minimap2 so that it reports identical CIGAR strings in the SA tag and the SA record. This would be helpful for a few reasons:

1. To my knowledge, the precedent with other aligners (such as BWA), is that the CIGAR strings in the SA tags will match those in the supplementary alignment record. This undocumented change can be confusing.
2. Existing tools developed using the precedent of 1. will need to be partially rewritten to account for this change.
3. It's somewhat misleading to include discordant information in the alignment records. This ambiguity wastes user's time by causing them to carefully (re)read the documentation and track down issues such as this to determine whether this is a bug. It would be better to leave the CIGAR field of the SA tag blank if it's expected to be inaccurate.

At a minimum, it would be helpful if the documentation was updated to clarify this point.

**Comment by fedarko** [comment]
Thank you both! I agree with Charles' points; if keeping the SA tag in the slightly inaccurate "shortened" format is necessary, then I propose that we update [minimap2's man page](https://lh3.github.io/minimap2/minimap2.html#10) to explain this. Maybe the following line:

https://github.com/lh3/minimap2/blob/bc588c0eeb26426d0d90a93fb0877358a389c515/minimap2.1#L699

could be changed to something like

```
SA	Z	List of other supplementary alignments (using approximate CIGAR strings)
```

This should make the situation much clearer. (If you'd prefer, we could also just add a link to this issue or to #287.)

If these changes seem reasonable, I would be happy to file a PR that updates the man page -- so that other users don't get stuck on this issue like we did.
